### PR TITLE
abdullah week3 hw

### PR DESCRIPTION
**Pull request by heartwhite**
server.js runs for homework week3(4actions).
index.js runs for command app (week2).

### CODE REVIEW

**Comment by heartwhite** [comment]
I updated my code. 
I noticed that it can be written in a better way. 
for now I just added actions to server.js (add, remove, update, list)
I will change all my code in this week

**Comment by heartwhite** [comment]
I updated my code.
I didn't use request body before. now I modified my create / update functions for this. now I accept a body exactly like example in homework description.
and I handled errors in each function separately.

**Comment by fedefu** [comment]
Hi there @Meno-101, @heartwhite and @gajduk. Is this approved or does it need to be redone? @heartwhite can you please take a look at it, discuss it with the teachers and let me know?

**Comment by gajduk** [comment]
Great job @heartwhite . You understand how to build a REST API and use the correct verbs and urls.
@fedefu  I approve this homework.

**Pull request closed without merging**
