### PR TITLE
Assignment week1

### PR DESCRIPTION
**Pull request by AbdulRahmanDbes**

### CODE REVIEW

**Comment by rts-rob** [comment]
Hi Abdul Rahman,

Lots of good stuff in here! One question - from the assignment:
```Javascript
// Any other URL
// Response: return error code 404: Not found with a friendly message
```

What is the HTTP Response Code that you return if I hit (for example) `/invalid/url` ?

**Comment by AbdulRahmanDbes** [comment]
Hi @rts-rob 
It should return an image, which I toke it from [Google](https://goo.gl/uu60ns)

`else print(response, request, "Error 404: Page Not Found");`

**Comment by rts-rob** [comment]
Right... but what status code are you returning? 

See this link from the week 1 README for a hint: http://www.restapitutorial.com/httpstatuscodes.html

**Comment by AbdulRahmanDbes** [comment]
@rts-rob Oh Right, I'm gonna fix it

Thanks ")

**Comment by daanaerts** [comment]
Cool, looks good

**Pull request closed without merging**
